#!/usr/bin/env python

import sys, os, shutil, subprocess

filename = sys.argv[1]
path = os.path.abspath(f"./figures/{filename}.svg")
pdf_path = os.path.abspath(f"./figures/{filename}.pdf")
if not os.path.isfile(path):
    exit()
subprocess.run(["inkscape", path,
                '--export-area-page',
            '--export-dpi', '300',
            '--export-type=pdf',
            '--export-latex',
            '--export-filename', pdf_path])