#!/usr/bin/env python

import sys, os, shutil, subprocess
import os.path as p

filename = sys.argv[1]
path = p.abspath(f"./figures/{filename}.svg")

template_dir = p.curdir
while "template.svg" not in os.listdir(template_dir):
    if p.abspath(template_dir) == p.abspath(template_dir+"/.."):
        print("Couldn't find figure template!")
        exit()
    template_dir += "/.."
template = template_dir + "/template.svg"

if not p.exists("./figures/"):
    os.makedirs("./figures/")
if not p.isfile(path):
    shutil.copyfile(template, path)

subprocess.Popen([r"C:\Program Files\Inkscape\bin\inkscape.exe", path], shell=True, )